### ISSUE TITLE
can't redirect to download link for mp3

### ISSUE THREAD

**Issue by GarryGon4ar** [GarryGon4ar/pyconverter#4]
[youtube] lRxBBiEdp6M: Downloading js player vflRCamp0
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/erl/intern/pyconverter/venv/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/erl/intern/pyconverter/venv/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/erl/intern/pyconverter/venv/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/erl/intern/pyconverter/venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by GarryGon4ar** [comment]
Updated youtubedl library
